version: "3"

services:
  db:
    image: mysql:8.0.30-debian
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tcc
    ports:
      - 3306:3306
    volumes:
      - ./.docker/mysql:/var/lib/mysql

  redis:
    image: redis:6.2.3-alpine
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    environment:
      NODE_ENV: development
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "10M"

  backend:
    build: ./backend
    container_name: backend
    restart: always
    ports:
      - 4000:4000
    volumes:
      - ./backend:/home/node/backend
    depends_on:
      - db
      - redis
    environment:
      NODE_ENV: development
      DATABASE_URL: mysql://root:root@db:3306/tcc
      SALT_OR_ROUNDS: $2b$10$9z70cN9X9MPw.MG7.75i0u
      JWT_SECRET: 50a68c38f44df8b84d9e95c4901260651b1d97622358878c3ff61814c26f8434
      JWT_EXPIRES_IN: 7d
      REDIS_PORT: 6379
      REDIS_HOST: redis
      FRONTEND_URL: http://localhost:3000
      SERVER_PORT: 4000
      CORS_ORIGIN: http://localhost:3000
    networks:
      - default

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/home/node/frontend
    depends_on:
      - backend
    environment:
      NODE_ENV: development
    networks:
      - default

networks:
  default:
    name: blflearng
