version: '3.9'

services:
  db:
    image: mysql:8.1.0
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tcc
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
  
  redis:
    image: redis:6.2.3-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    environment:
      NODE_ENV: development
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '10M'
  
  # api:
  #   build: .
  #   container_name: api
  #   restart: always
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     NODE_ENV: development
  #     PORT: 3000
  #     DATABASE_URL: mysql://root:root@db:3306/tcc
  #     SALT_OR_ROUNDS: 10
  #     JWT_SECRET: 50a68c38f44df8b84d9e95c4901260651b1d97622358878c3ff61814c26f8434
  #     JWT_EXPIRATION_TIME: 7d
  #     REDIS_HOST: redis
  #     REDIS_PORT: 6379
  #   depends_on:
  #     - db
  #     - redis
  #   networks:
  #     - default

networks:
  default:
    name: nestjs_network_default